### ISSUE TITLE
HMR Support

### ISSUE THREAD

**Issue by abhishiv** [vobyjs/voby#15]
Hello, for many use cases having a true HMR would be amazing. Direct manipulation editors for example. 

> `VOBY_HMR`: If `true`, then Voby will catch errors that happen during diffing and log them to the console instead, keeping your page working after an HMR update event in some case. Fine-grainined support for HMR is not implemented (yet?).

But as far as I can see it's not implemented yet? What kind of pitfals should one expect with HMR while using voby?

**Comment by fabiospampinato** [comment]
> But as far as I can see it's not implemented yet? What kind of pitfals should one expect with HMR while using voby?

Proper fine-grained HMR is not implemented. But if you set that global to `true` then the framework will keep working under HMR under more scenarios. It's a bit of a hack but it improves the experience enough to be worth it.

I don't know if full fine-grained HMR will be implemented. If you don't use css-in-js and instead use something like SASS, which you should probably do already, most of the value of HMR, for most cases, disappears. There's still some value in it, and potentially a lot of value in it in other scenarios, but HMR is a significant additional complication and I don't think I've ever seen an HMR implementation that actually works and that can be trusted. 

Maybe I'll try to implement this in the future, especially if the framework grows significantly and people request this, we'll see.
