### ISSUE TITLE
Enhance the type of createDirective

### ISSUE THREAD

**Issue by FlatMapIO** [vobyjs/voby#21]
Thanks for the tip in #20 , I played with it a bit, it's really handy, I suggest to improve the type of createDirective to make it more typeify, here is my code, it provides name and opts type

<img width="668" alt="image" src="https://user-images.githubusercontent.com/1720349/220232900-7bf33ed8-c61d-4281-9a9a-0bed12885e8d.png">

**Comment by fabiospampinato** [comment]
Oh definitely, thanks for the suggestion 👍

**Comment by fabiospampinato** [comment]
Implemented, I'll make the v0.45 release as soon as I'm done with some other things. Thank you.
