### ISSUE TITLE
`store.unwrap(...)` is not appropriately typed

### ISSUE THREAD

**Issue by theSherwood** [vobyjs/voby#29]
I like to unwrap stores for logging to the console as the Proxies require a couple extra clicks to see the value. So I'm using `store.unwrap` but doesn't appear to be part present on the `store` type. Are you planning on a different `unwrap` function or do you not want to publicly expose it?

**Comment by fabiospampinato** [comment]
I can't reproduce the issue, it's picked up by TS for me.

<img width="821" alt="Screen Shot 2023-09-30 at 11 43 35" src="https://github.com/vobyjs/voby/assets/1812093/aafe45f2-cf5a-4102-b41b-1bfd5ed9cae3">

I guess potentially it could be renamed in the future, but something like this is necessary.

**Comment by theSherwood** [comment]
Ah. Okay. Apologies. I'm not able to reproduce the issue now. It's possible I was on a previous version or something. Feel free to close.
