### ISSUE TITLE
createContext with a factory lambda

### ISSUE THREAD

**Issue by derolf** [vobyjs/voby#31]
Currently, we have:

```
function createContext <T> ( defaultValue?: T ): Context<T>;
```

That means all instances of the context have the same defaultValue.

It would be nice to have:

```
function createContext <T> ( factory: () => T ): Context<T>;
```

**Comment by fabiospampinato** [comment]
What's the use case where this would be useful? 🤔

**Comment by fabiospampinato** [comment]
Closing for lack of answer, and in general I don't really thing is necessary.
