### ISSUE TITLE
useResource does not properly guard against outdated promises

### ISSUE THREAD

**Issue by derolf** [vobyjs/voby#33]
Clicking quickly on "increment" in https://stackblitz.com/edit/vitejs-vite-69hjfc?file=src%2Fcounter.tsx makes the Suspense leak.

I assume that useResource does not "drop" a promise that is outdated.

Example: https://gist.github.com/derolf/77dfbd21ac6804537c4927590af16aad#file-observablefrompromise-ts-L25

**Comment by fabiospampinato** [comment]
Fixed in latest
