### ISSUE TITLE
Dependency tracking is buggy

### ISSUE THREAD

**Issue by hiddenMedic** [vobyjs/voby#36]
Reproduction:
https://playground.solidjs.com/anonymous/ec132058-6494-4b42-ae52-fe61ed786b15
Pressing the +/- button does nothing with the `console.log(value());` line added.

**Comment by fabiospampinato** [comment]
Interesting, I can reproduce the issue locally, let me have a look at this 🤔

**Comment by fabiospampinato** [comment]
Fixed in v0.57.4, I was forgetting to untrack the function to render, because when using JSX normally one would write `render(<App>,...)` so that happens implicitly, I had to make sure it happened explicitly.
