### ISSUE TITLE
Prevent closure variables caching issue

### ISSUE THREAD

**Issue by Mati365** [vobyjs/voby#9]
https://github.com/vobyjs/voby/blob/d685d6079bb0172339d26535a551842545c70ab3/src/hooks/use_timeout.ts#L15

Maybe it will be better to use there (and in other places) "safe closure" approach? It is described here: https://dmitripavlutin.com/react-hooks-stale-closures/

**Comment by fabiospampinato** [comment]
How do you propose that code should be changed? And I guess what would that change bring to the table>
